library(SternBrocotPhysics)
library(data.table)

# --- CONFIGURATION ---
data_dir <- "/Volumes/SanDisk4TB/SternBrocot-data/06_bell_test"

# --- 1. DIRECTORY MANAGEMENT ---
if (dir.exists(data_dir)) {
  unlink(data_dir, recursive = TRUE)
}
dir.create(data_dir, recursive = TRUE)

# --- 2. RUN SIMULATION ---
alice_angles_rad <- c(0.0, pi/2) + 1e-5
bob_angles_rad   <- seq(0, 2 * pi, by = 0.01) + 1e-5

message("Generating raw simulation data...")
# FIX: Cast count and threads to strict integers (10000L, 6L) for Rcpp type safety
# The microstate bounds (0.0, 2*pi) remain continuous doubles.
micro_macro_bell_erasure_sweep('alice', alice_angles_rad, normalizePath(data_dir), 10000L, 0.0, 2*pi, 6L)
micro_macro_bell_erasure_sweep('bob', bob_angles_rad, normalizePath(data_dir), 10000L, 0.0, 2*pi, 6L)

# --- 3. DYNAMIC DATA DISCOVERY ---
all_files   <- list.files(data_dir, pattern = "erasure_.*\\.csv\\.gz")
alice_files <- grep("alice", all_files, value = TRUE)
bob_files   <- grep("bob", all_files, value = TRUE)

parse_angle <- function(file_names) {
  # This correctly grabs the negative angles generated by C++ std::remainder
  extracted_strings <- gsub("erasure_[^_]+_([-0-9.]+)\\.csv\\.gz", "\\1", file_names)
  as.numeric(extracted_strings)
}

# --- 4. DATA REFLECTION & JOIN ---
message("Reflecting on filesystem to build summary...")

names(alice_files) <- alice_files

alice_data_list <- lapply(alice_files, function(f) {
  fread(file.path(data_dir, f), select = c("spin", "found"))
})

alice_numeric_angles <- parse_angle(alice_files)
sorted_idx           <- order(alice_numeric_angles)

# file_key_0 will naturally map to the ~0 rad file
# file_key_90 will naturally map to the ~1.57 rad file
file_key_0  <- alice_files[sorted_idx[1]]
file_key_90 <- alice_files[sorted_idx[2]]

correlation_summary <- rbindlist(lapply(bob_files, function(bob_file) {

  current_bob_angle <- parse_angle(bob_file)
  bob_dt <- fread(file.path(data_dir, bob_file), select = c("spin", "found"))

  alice_0  <- alice_data_list[[file_key_0]]
  alice_90 <- alice_data_list[[file_key_90]]

  mask_0  <- alice_0$found  & bob_dt$found
  mask_90 <- alice_90$found & bob_dt$found

  data.table(
    bob_angle_rad        = current_bob_angle, # NOTE: This will range from -pi to pi
    correlation_alice_0  = -mean(as.numeric(alice_0$spin[mask_0])  * as.numeric(bob_dt$spin[mask_0]), na.rm = TRUE),
    correlation_alice_90 = -mean(as.numeric(alice_90$spin[mask_90]) * as.numeric(bob_dt$spin[mask_90]), na.rm = TRUE)
  )
}))

# --- 5. PREP FOR RMD & PERSIST ---
# The modulo `%% (2 * pi)` elegantly wraps the [-pi, pi] angles back to positive for plotting
correlation_summary[, phase_diff_90 := (bob_angle_rad - pi/2) %% (2 * pi)]
setorder(correlation_summary, phase_diff_90)

fwrite(correlation_summary, file.path(data_dir, "summary_stats.csv.gz"))

message(sprintf("Done. Summary built using Alice files: %s and %s", file_key_0, file_key_90))
