// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// micro_macro_bell_erasure_sweep
void micro_macro_bell_erasure_sweep(NumericVector detector_angles, std::string dir, int count, double angular_momentum, double microstate_particle_angle_start, double microstate_particle_angle_end, int n_threads);
RcppExport SEXP _SternBrocotPhysics_micro_macro_bell_erasure_sweep(SEXP detector_anglesSEXP, SEXP dirSEXP, SEXP countSEXP, SEXP angular_momentumSEXP, SEXP microstate_particle_angle_startSEXP, SEXP microstate_particle_angle_endSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type detector_angles(detector_anglesSEXP);
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type angular_momentum(angular_momentumSEXP);
    Rcpp::traits::input_parameter< double >::type microstate_particle_angle_start(microstate_particle_angle_startSEXP);
    Rcpp::traits::input_parameter< double >::type microstate_particle_angle_end(microstate_particle_angle_endSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    micro_macro_bell_erasure_sweep(detector_angles, dir, count, angular_momentum, microstate_particle_angle_start, microstate_particle_angle_end, n_threads);
    return R_NilValue;
END_RCPP
}
// erase_by_uncertainty
DataFrame erase_by_uncertainty(NumericVector x, double uncertainty);
RcppExport SEXP _SternBrocotPhysics_erase_by_uncertainty(SEXP xSEXP, SEXP uncertaintySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    rcpp_result_gen = Rcpp::wrap(erase_by_uncertainty(x, uncertainty));
    return rcpp_result_gen;
END_RCPP
}
// erase_uncertainty_bounded
DataFrame erase_uncertainty_bounded(NumericVector x, double uncertainty, double lower_bound, double upper_bound, double lower_action, double upper_action);
RcppExport SEXP _SternBrocotPhysics_erase_uncertainty_bounded(SEXP xSEXP, SEXP uncertaintySEXP, SEXP lower_boundSEXP, SEXP upper_boundSEXP, SEXP lower_actionSEXP, SEXP upper_actionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    Rcpp::traits::input_parameter< double >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< double >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< double >::type lower_action(lower_actionSEXP);
    Rcpp::traits::input_parameter< double >::type upper_action(upper_actionSEXP);
    rcpp_result_gen = Rcpp::wrap(erase_uncertainty_bounded(x, uncertainty, lower_bound, upper_bound, lower_action, upper_action));
    return rcpp_result_gen;
END_RCPP
}
// erase_by_depth
DataFrame erase_by_depth(NumericVector x, int depth);
RcppExport SEXP _SternBrocotPhysics_erase_by_depth(SEXP xSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(erase_by_depth(x, depth));
    return rcpp_result_gen;
END_RCPP
}
// erase_by_uncertainty_and_depth
DataFrame erase_by_uncertainty_and_depth(NumericVector x, double uncertainty, int depth);
RcppExport SEXP _SternBrocotPhysics_erase_by_uncertainty_and_depth(SEXP xSEXP, SEXP uncertaintySEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty(uncertaintySEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(erase_by_uncertainty_and_depth(x, uncertainty, depth));
    return rcpp_result_gen;
END_RCPP
}
// erasures
void erasures(NumericVector momenta, std::string dir, int n_threads);
RcppExport SEXP _SternBrocotPhysics_erasures(SEXP momentaSEXP, SEXP dirSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type momenta(momentaSEXP);
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    erasures(momenta, dir, n_threads);
    return R_NilValue;
END_RCPP
}
// count_nodes_cpp
DataFrame count_nodes_cpp(DataFrame sub_df, NumericVector thresh_vec);
RcppExport SEXP _SternBrocotPhysics_count_nodes_cpp(SEXP sub_dfSEXP, SEXP thresh_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sub_df(sub_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thresh_vec(thresh_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(count_nodes_cpp(sub_df, thresh_vec));
    return rcpp_result_gen;
END_RCPP
}
// pib_erasures
void pib_erasures(NumericVector momenta, std::string dir, int n_threads);
RcppExport SEXP _SternBrocotPhysics_pib_erasures(SEXP momentaSEXP, SEXP dirSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type momenta(momentaSEXP);
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    pib_erasures(momenta, dir, n_threads);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SternBrocotPhysics_micro_macro_bell_erasure_sweep", (DL_FUNC) &_SternBrocotPhysics_micro_macro_bell_erasure_sweep, 7},
    {"_SternBrocotPhysics_erase_by_uncertainty", (DL_FUNC) &_SternBrocotPhysics_erase_by_uncertainty, 2},
    {"_SternBrocotPhysics_erase_uncertainty_bounded", (DL_FUNC) &_SternBrocotPhysics_erase_uncertainty_bounded, 6},
    {"_SternBrocotPhysics_erase_by_depth", (DL_FUNC) &_SternBrocotPhysics_erase_by_depth, 2},
    {"_SternBrocotPhysics_erase_by_uncertainty_and_depth", (DL_FUNC) &_SternBrocotPhysics_erase_by_uncertainty_and_depth, 3},
    {"_SternBrocotPhysics_erasures", (DL_FUNC) &_SternBrocotPhysics_erasures, 3},
    {"_SternBrocotPhysics_count_nodes_cpp", (DL_FUNC) &_SternBrocotPhysics_count_nodes_cpp, 2},
    {"_SternBrocotPhysics_pib_erasures", (DL_FUNC) &_SternBrocotPhysics_pib_erasures, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SternBrocotPhysics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
