// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// harmonic_oscillator_erasures
void harmonic_oscillator_erasures(NumericVector momenta, std::string dir, std::string algorithm, int n_threads);
RcppExport SEXP _SternBrocotPhysics_harmonic_oscillator_erasures(SEXP momentaSEXP, SEXP dirSEXP, SEXP algorithmSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type momenta(momentaSEXP);
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< std::string >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    harmonic_oscillator_erasures(momenta, dir, algorithm, n_threads);
    return R_NilValue;
END_RCPP
}
// kdtree_erase_max_erasure_radius
DataFrame kdtree_erase_max_erasure_radius(NumericVector x, double max_erasure_radius);
RcppExport SEXP _SternBrocotPhysics_kdtree_erase_max_erasure_radius(SEXP xSEXP, SEXP max_erasure_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type max_erasure_radius(max_erasure_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(kdtree_erase_max_erasure_radius(x, max_erasure_radius));
    return rcpp_result_gen;
END_RCPP
}
// kdtree_erase_depth
DataFrame kdtree_erase_depth(NumericVector x, int depth);
RcppExport SEXP _SternBrocotPhysics_kdtree_erase_depth(SEXP xSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(kdtree_erase_depth(x, depth));
    return rcpp_result_gen;
END_RCPP
}
// kdtree_erase_max_erasure_radius_and_depth
DataFrame kdtree_erase_max_erasure_radius_and_depth(NumericVector x, double max_erasure_radius, int depth);
RcppExport SEXP _SternBrocotPhysics_kdtree_erase_max_erasure_radius_and_depth(SEXP xSEXP, SEXP max_erasure_radiusSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type max_erasure_radius(max_erasure_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(kdtree_erase_max_erasure_radius_and_depth(x, max_erasure_radius, depth));
    return rcpp_result_gen;
END_RCPP
}
// count_nodes_cpp
DataFrame count_nodes_cpp(DataFrame sub_df, NumericVector thresh_vec);
RcppExport SEXP _SternBrocotPhysics_count_nodes_cpp(SEXP sub_dfSEXP, SEXP thresh_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type sub_df(sub_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thresh_vec(thresh_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(count_nodes_cpp(sub_df, thresh_vec));
    return rcpp_result_gen;
END_RCPP
}
// stern_brocot_erase_max_erasure_radius
DataFrame stern_brocot_erase_max_erasure_radius(NumericVector x, double max_erasure_radius);
RcppExport SEXP _SternBrocotPhysics_stern_brocot_erase_max_erasure_radius(SEXP xSEXP, SEXP max_erasure_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type max_erasure_radius(max_erasure_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(stern_brocot_erase_max_erasure_radius(x, max_erasure_radius));
    return rcpp_result_gen;
END_RCPP
}
// stern_brocot_erase_depth
DataFrame stern_brocot_erase_depth(NumericVector x, int depth);
RcppExport SEXP _SternBrocotPhysics_stern_brocot_erase_depth(SEXP xSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(stern_brocot_erase_depth(x, depth));
    return rcpp_result_gen;
END_RCPP
}
// stern_brocot_erase_max_erasure_radius_and_depth
DataFrame stern_brocot_erase_max_erasure_radius_and_depth(NumericVector x, double max_erasure_radius, int depth);
RcppExport SEXP _SternBrocotPhysics_stern_brocot_erase_max_erasure_radius_and_depth(SEXP xSEXP, SEXP max_erasure_radiusSEXP, SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type max_erasure_radius(max_erasure_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(stern_brocot_erase_max_erasure_radius_and_depth(x, max_erasure_radius, depth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SternBrocotPhysics_harmonic_oscillator_erasures", (DL_FUNC) &_SternBrocotPhysics_harmonic_oscillator_erasures, 4},
    {"_SternBrocotPhysics_kdtree_erase_max_erasure_radius", (DL_FUNC) &_SternBrocotPhysics_kdtree_erase_max_erasure_radius, 2},
    {"_SternBrocotPhysics_kdtree_erase_depth", (DL_FUNC) &_SternBrocotPhysics_kdtree_erase_depth, 2},
    {"_SternBrocotPhysics_kdtree_erase_max_erasure_radius_and_depth", (DL_FUNC) &_SternBrocotPhysics_kdtree_erase_max_erasure_radius_and_depth, 3},
    {"_SternBrocotPhysics_count_nodes_cpp", (DL_FUNC) &_SternBrocotPhysics_count_nodes_cpp, 2},
    {"_SternBrocotPhysics_stern_brocot_erase_max_erasure_radius", (DL_FUNC) &_SternBrocotPhysics_stern_brocot_erase_max_erasure_radius, 2},
    {"_SternBrocotPhysics_stern_brocot_erase_depth", (DL_FUNC) &_SternBrocotPhysics_stern_brocot_erase_depth, 2},
    {"_SternBrocotPhysics_stern_brocot_erase_max_erasure_radius_and_depth", (DL_FUNC) &_SternBrocotPhysics_stern_brocot_erase_max_erasure_radius_and_depth, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SternBrocotPhysics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
