# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
micro_macro_bell_erasure_sweep <- function(angles, dir, count, kappa, mu_start, mu_end, n_threads = 0L) {
    invisible(.Call(`_SternBrocotPhysics_micro_macro_bell_erasure_sweep`, angles, dir, count, kappa, mu_start, mu_end, n_threads))
}

erase_by_uncertainty <- function(x, uncertainty) {
    .Call(`_SternBrocotPhysics_erase_uncertainty`, x, uncertainty)
}

erase_by_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_erase_depth`, x, depth)
}

erase_by_uncertainty_and_depth <- function(x, uncertainty, depth) {
    .Call(`_SternBrocotPhysics_erase_uncertainty_and_depth`, x, uncertainty, depth)
}

#' @export
micro_macro_erasures_momentum <- function(momenta, dir, count, n_threads = 0L) {
    invisible(.Call(`_SternBrocotPhysics_micro_macro_erasures_momentum`, momenta, dir, count, n_threads))
}

#' Detect Oscillatory Nodes in Physical State Density
#'
#' @param sub_df A DataFrame containing 'x' and 'y'.
#' @param thresh The sensitivity threshold.
#' @param global_h_range The total range of the histogram counts.
#' @return A DataFrame of detected node coordinates (x, y).
#' @export
find_nodes_cpp <- function(sub_df, thresh, global_h_range) {
    .Call(`_SternBrocotPhysics_find_nodes_cpp`, sub_df, thresh, global_h_range)
}

#' @export
contains_peak_cpp <- function(sub_df, thresh, global_h_range) {
    .Call(`_SternBrocotPhysics_contains_peak_cpp`, sub_df, thresh, global_h_range)
}

