# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
micro_macro_bell_erasure_sweep <- function(detector_angles, dir, count, angular_momentum, microstate_particle_angle_start, microstate_particle_angle_end, n_threads = 0L) {
    invisible(.Call(`_SternBrocotPhysics_micro_macro_bell_erasure_sweep`, detector_angles, dir, count, angular_momentum, microstate_particle_angle_start, microstate_particle_angle_end, n_threads))
}

erase_by_uncertainty <- function(x, uncertainty) {
    .Call(`_SternBrocotPhysics_erase_uncertainty`, x, uncertainty)
}

erase_by_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_erase_depth`, x, depth)
}

erase_by_uncertainty_and_depth <- function(x, uncertainty, depth) {
    .Call(`_SternBrocotPhysics_erase_uncertainty_and_depth`, x, uncertainty, depth)
}

erasures <- function(momenta, dir, n_threads = 0L) {
    invisible(.Call(`_SternBrocotPhysics_erasures`, momenta, dir, n_threads))
}

#' Detect Significant Physical Features (Hysteresis)
#'
#' @param sub_df DataFrame with x (coordinate) and y (density)
#' @param thresh_vec Vector of adaptive thresholds matching sub_df rows
#' @export
count_nodes_cpp <- function(sub_df, thresh_vec) {
    .Call(`_SternBrocotPhysics_count_nodes_cpp`, sub_df, thresh_vec)
}

