# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

action_angle_erase_squeezed_boundary <- function(x, squeezed_boundary) {
    .Call(`_SternBrocotPhysics_action_angle_erase_squeezed_boundary`, x, squeezed_boundary)
}

action_angle_erase_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_action_angle_erase_depth`, x, depth)
}

action_angle_erase_squeezed_boundary_and_depth <- function(x, squeezed_boundary, depth) {
    .Call(`_SternBrocotPhysics_action_angle_erase_squeezed_boundary_and_depth`, x, squeezed_boundary, depth)
}

golden_ratio_erase_squeezed_boundary <- function(x, squeezed_boundary) {
    .Call(`_SternBrocotPhysics_golden_ratio_erase_squeezed_boundary`, x, squeezed_boundary)
}

golden_ratio_erase_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_golden_ratio_erase_depth`, x, depth)
}

golden_ratio_erase_squeezed_boundary_and_depth <- function(x, squeezed_boundary, depth) {
    .Call(`_SternBrocotPhysics_golden_ratio_erase_squeezed_boundary_and_depth`, x, squeezed_boundary, depth)
}

#' Run Erasure Simulation
NULL

harmonic_oscillator_erasures <- function(momenta, dir, algorithm = "stern_brocot", n_threads = 0L) {
    invisible(.Call(`_SternBrocotPhysics_harmonic_oscillator_erasures`, momenta, dir, algorithm, n_threads))
}

kdtree_erase_squeezed_boundary <- function(x, squeezed_boundary) {
    .Call(`_SternBrocotPhysics_kdtree_erase_squeezed_boundary`, x, squeezed_boundary)
}

kdtree_erase_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_kdtree_erase_depth`, x, depth)
}

kdtree_erase_squeezed_boundary_and_depth <- function(x, squeezed_boundary, depth) {
    .Call(`_SternBrocotPhysics_kdtree_erase_squeezed_boundary_and_depth`, x, squeezed_boundary, depth)
}

#' Detect Significant Physical Features (Standard Hysteresis)
#'
#' @param sub_df DataFrame with x (coordinate) and y (density)
#' @param thresh_vec Vector of adaptive thresholds matching sub_df rows
#' @export
count_nodes_cpp <- function(sub_df, thresh_vec) {
    .Call(`_SternBrocotPhysics_count_nodes_cpp`, sub_df, thresh_vec)
}

stern_brocot_erase_squeezed_boundary <- function(x, squeezed_boundary) {
    .Call(`_SternBrocotPhysics_stern_brocot_erase_squeezed_boundary`, x, squeezed_boundary)
}

stern_brocot_erase_depth <- function(x, depth) {
    .Call(`_SternBrocotPhysics_stern_brocot_erase_depth`, x, depth)
}

stern_brocot_erase_squeezed_boundary_and_depth <- function(x, squeezed_boundary, depth) {
    .Call(`_SternBrocotPhysics_stern_brocot_erase_squeezed_boundary_and_depth`, x, squeezed_boundary, depth)
}

